maestro:
  data_types:
    'motorl':
      type: 'output'
      range: [-1,1]
      accel: 10
    'motorr':
      type: 'output'
      range: [1,-1]
      accel: 10

  device:
    'thruster_left':
      'pin': 1
      'data_type': 'motorl'
    'thruster_right':
      'pin': 0
      'data_type': 'motorr'